package com.goyimatica.synaxismobile.core

/* The movable cycle: offset from Pascha → what is kept. */
val MOVABLE: Map<Long, Feast> = mapOf(
    -70L to Feast("Sunday of the Publican and the Pharisee", "The Triodion opens; the week that follows is fast-free", movable = true),
    -63L to Feast("Sunday of the Prodigal Son", movable = true),
    -57L to Feast("Saturday of Souls", "Meatfare Saturday — all the departed are remembered", movable = true),
    -56L to Feast("Sunday of the Last Judgement", "Meatfare Sunday — the last day for meat", movable = true),
    -50L to Feast("Sunday of Forgiveness", "Cheesefare — the expulsion of Adam from Paradise; forgiveness vespers in the evening", movable = true),
    -48L to Feast("Clean Monday", "Great Lent begins", movable = true),
    -43L to Feast("St Theodore the Recruit", "First Saturday of Lent — the miracle of the kolyva", movable = true),
    -42L to Feast("Sunday of Orthodoxy", "The restoration of the holy icons, 843", great = true, movable = true),
    -36L to Feast("Saturday of Souls", "Second Saturday of Great Lent", movable = true),
    -35L to Feast("St Gregory Palamas", "Second Sunday of Lent — the uncreated light", movable = true),
    -29L to Feast("Saturday of Souls", "Third Saturday of Great Lent", movable = true),
    -28L to Feast("Veneration of the Holy Cross", "Mid-Lent; the Cross is brought out for veneration", great = true, movable = true),
    -22L to Feast("Saturday of Souls", "Fourth Saturday of Great Lent", movable = true),
    -21L to Feast("St John Climacus", "Fourth Sunday of Lent — the Ladder of Divine Ascent", movable = true),
    -17L to Feast("The Great Canon of St Andrew", "Thursday of the fifth week; wine and oil are allowed for the vigil", movable = true),
    -16L to Feast("The Akathist to the Theotokos", "Friday of the fifth week — the Laudation of the Mother of God", movable = true),
    -15L to Feast("Saturday of the Akathist", "The Laudation of the Theotokos", movable = true),
    -14L to Feast("St Mary of Egypt", "Fifth Sunday of Lent", movable = true),
    -8L to Feast("Lazarus Saturday", "The raising of Lazarus; caviar is allowed by custom", great = true, movable = true),
    -7L to Feast("Palm Sunday", "The Entry of the Lord into Jerusalem — a Great Feast; fish is allowed", great = true, movable = true),
    -6L to Feast("Great and Holy Monday", "Joseph the all-comely and the barren fig tree", movable = true),
    -5L to Feast("Great and Holy Tuesday", "The ten virgins", movable = true),
    -4L to Feast("Great and Holy Wednesday", "The sinful woman who anointed His feet; Holy Unction", movable = true),
    -3L to Feast("Great and Holy Thursday", "The Mystical Supper", great = true, movable = true),
    -2L to Feast("Great and Holy Friday", "The Passion and burial of the Lord — the strictest day of the year", great = true, movable = true),
    -1L to Feast("Great and Holy Saturday", "The Lord rests in the tomb; the harrowing of Hades", great = true, movable = true),
    0L to Feast("PASCHA — The Resurrection of Christ", "The Feast of Feasts. Christ is risen!", great = true, movable = true),
    1L to Feast("Bright Monday", "Bright Week — fast-free", movable = true),
    2L to Feast("Bright Tuesday", "The Iveron icon by Greek custom", movable = true),
    3L to Feast("Bright Wednesday", movable = true),
    4L to Feast("Bright Thursday", movable = true),
    5L to Feast("Bright Friday", "The Life-giving Spring of the Theotokos", movable = true),
    6L to Feast("Bright Saturday", movable = true),
    7L to Feast("Thomas Sunday", "Antipascha — the doubting and confession of Thomas", great = true, movable = true),
    9L to Feast("Radonitsa", "The Paschal remembrance of the departed (Slavic use)", movable = true),
    14L to Feast("Sunday of the Myrrh-bearing Women", "With Joseph of Arimathea and Nicodemus", movable = true),
    21L to Feast("Sunday of the Paralytic", movable = true),
    24L to Feast("Mid-Pentecost", "Wednesday of the fourth week of Pascha", movable = true),
    28L to Feast("Sunday of the Samaritan Woman", "St Photini", movable = true),
    35L to Feast("Sunday of the Blind Man", movable = true),
    39L to Feast("The Ascension of the Lord", "A Great Feast — always a Thursday", great = true, movable = true),
    42L to Feast("The Fathers of the First Council", "Nicaea, 325 — seventh Sunday of Pascha", movable = true),
    48L to Feast("Saturday of Souls", "Trinity Saturday — all the departed from the ages", movable = true),
    49L to Feast("PENTECOST — The Holy Trinity", "The descent of the Holy Spirit; a Great Feast. The week that follows is fast-free", great = true, movable = true),
    50L to Feast("Monday of the Holy Spirit", "Spirit Monday", movable = true),
    56L to Feast("All Saints", "First Sunday after Pentecost", movable = true),
    57L to Feast("The Apostles' Fast begins", "It runs to the eve of Ss Peter and Paul, so its length changes every year", movable = true),
    63L to Feast("All Saints of Russia, and of every local Church", "Second Sunday after Pentecost", movable = true),
)

/* The fixed cycle, keyed by CHURCH date — not by the civil date. On the Old
   Calendar, church 12-25 is civil 7 January. */
val FIXED: Map<String, Feast> = mapOf(
    "01-01" to Feast("The Circumcision of the Lord; St Basil the Great"),
    "01-05" to Feast("The Eve of Theophany", "A day of strict fasting"),
    "01-06" to Feast("THEOPHANY — The Baptism of the Lord", "A Great Feast; the Great Blessing of Water", great = true),
    "01-07" to Feast("The Synaxis of St John the Forerunner"),
    "01-30" to Feast("The Three Hierarchs", "Basil the Great, Gregory the Theologian, John Chrysostom"),
    "02-02" to Feast("THE MEETING OF THE LORD", "The Presentation in the Temple — a Great Feast", great = true),
    "02-24" to Feast("The First and Second Finding of the Head of St John the Forerunner"),
    "03-09" to Feast("The Forty Martyrs of Sebaste"),
    "03-25" to Feast("THE ANNUNCIATION", "A Great Feast. Fish is allowed even in Great Lent", great = true),
    "04-23" to Feast("St George the Great Martyr and Victory-bearer"),
    "04-25" to Feast("The Holy Apostle and Evangelist Mark"),
    "05-08" to Feast("St John the Theologian"),
    "05-09" to Feast("The Translation of the relics of St Nicholas"),
    "05-11" to Feast("Ss Cyril and Methodius, teachers of the Slavs"),
    "05-21" to Feast("Ss Constantine and Helen, Equal to the Apostles"),
    "06-24" to Feast("The Nativity of St John the Forerunner"),
    "06-29" to Feast("THE HOLY APOSTLES PETER AND PAUL", "The Apostles' Fast ends", great = true),
    "06-30" to Feast("The Synaxis of the Twelve Apostles"),
    "07-05" to Feast("St Sergius of Radonezh"),
    "07-11" to Feast("St Euphemia; St Olga of Kiev"),
    "07-15" to Feast("St Vladimir, Equal to the Apostles", "The baptism of Rus"),
    "07-17" to Feast("The Royal Martyrs of Russia", "Tsar Nicholas II and his family"),
    "07-20" to Feast("The Holy Prophet Elias"),
    "08-01" to Feast("The Procession of the Precious Cross", "The Dormition Fast begins"),
    "08-06" to Feast("THE TRANSFIGURATION OF THE LORD", "A Great Feast; fish is allowed, and grapes are blessed", great = true),
    "08-15" to Feast("THE DORMITION OF THE THEOTOKOS", "A Great Feast — the falling-asleep of the Mother of God", great = true),
    "08-16" to Feast("The Icon of Christ Not-Made-by-Hands"),
    "08-29" to Feast("The Beheading of St John the Forerunner", "A day of strict fasting whatever the day of the week"),
    "09-01" to Feast("The Beginning of the Church Year", "The Indiction"),
    "09-08" to Feast("THE NATIVITY OF THE THEOTOKOS", "A Great Feast — the first of the year", great = true),
    "09-14" to Feast("THE ELEVATION OF THE PRECIOUS CROSS", "A Great Feast, kept with fasting", great = true),
    "09-26" to Feast("The Repose of St John the Theologian"),
    "10-01" to Feast("The Protection of the Theotokos", "The Pokrov — her veil over the world"),
    "10-26" to Feast("St Demetrius of Thessalonica"),
    "11-08" to Feast("The Synaxis of the Archangel Michael and all the Bodiless Powers"),
    "11-13" to Feast("St John Chrysostom"),
    "11-15" to Feast("The Nativity Fast begins", "Forty days to the Nativity — St Philip's Fast"),
    "11-21" to Feast("THE ENTRANCE OF THE THEOTOKOS INTO THE TEMPLE", "A Great Feast; fish is allowed", great = true),
    "11-30" to Feast("The Holy Apostle Andrew the First-called"),
    "12-04" to Feast("St Barbara the Great Martyr; St John of Damascus"),
    "12-06" to Feast("St Nicholas of Myra, the Wonderworker"),
    "12-09" to Feast("The Conception of the Theotokos by St Anna"),
    "12-12" to Feast("St Spyridon the Wonderworker"),
    "12-17" to Feast("The Holy Prophet Daniel and the Three Youths"),
    "12-20" to Feast("St John of Kronstadt"),
    "12-24" to Feast("The Eve of the Nativity", "Nothing is eaten until the first star, by custom"),
    "12-25" to Feast("THE NATIVITY OF CHRIST", "A Great Feast. Twelve fast-free days follow, to the eve of Theophany", great = true),
    "12-26" to Feast("The Synaxis of the Most Holy Theotokos"),
    "12-27" to Feast("The Holy Protomartyr and Archdeacon Stephen"),
)